name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
version-template: $MAJOR.$MINOR
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES
replacers:
  - search: '/((OPA|PAR)-\d+):?/g'
    replace: '[$1](https://postinext.atlassian.net/browse/$1)'
categories:
  - title: 'Features'
    labels:
      - 'feat'
      - 'feature'
  - title: 'Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: 'Internal'
    labels:
      - 'chore'
      - 'internal'
exclude-labels:
  - 'skip-changelog'
