#!/usr/bin/env bash

set -eo pipefail

# Helper to find relevant tags from Github releases

# Limiting release search to first 20 releses, documentation does not say clearly that results are shown by
# creation order latest first, but that seems to be the case. There anyway should only be one/zero meaningful
# draft release and max couple of pre-releases on the fly in the top hits.

fetch_releases() {
  hub release --include-drafts -L 20 \
    -f '{"tag": "%T", "type":"%S", "created":"%ct"}%n'
}

find_release() {
  local selector=$1
  jq -s -r '
    map('"$selector"') |
    sort_by(.created) |
    reverse |
    first |
    .tag // empty
  '
}

find_release_by_type() {
  local type=$1
  find_release "select(.type==\"$type\")"
}

find_rc_prerelease() {
  find_release 'select(
    (.type=="pre-release") and
    (.tag | contains("rc")) and
    (.tag | contains("hotfix") | not)
  )'
}

find_hotfix_prerelease() {
  find_release 'select(
    (.type=="pre-release") and
    (.tag | contains("hotfix"))
  )'
}

fetch_latest_tag_names() {
  local releases
  releases=$(fetch_releases)
  LATEST_DRAFT_TAG=$(echo "$releases" | find_release_by_type 'draft')
  LATEST_RC_PREREL_TAG=$(echo "$releases" | find_rc_prerelease)
  LATEST_HOTFIX_PREREL_TAG=$(echo "$releases" | find_hotfix_prerelease)
  LATEST_RELEASE_TAG=$(echo "$releases" | find_release_by_type '')
  echo "Latest draft release tag: $LATEST_DRAFT_TAG"
  echo "Latest rc prerelease tag: $LATEST_RC_PREREL_TAG"
  echo "Latest hotfix prerelease tag: $LATEST_HOTFIX_PREREL_TAG"
  echo "Latest release tag: $LATEST_RELEASE_TAG"
}

if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
  "$@"
fi
