name: Keep release candidate up to date on pushes to rc

on:
  push:
    branches:
      - rc

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: cache
        uses: actions/cache@v1
        with:
          path: /opt/bin
          key: opt-bin-hub-1

      - name: Install hub
        if: steps.cache.outputs.cache-hit != 'true'
        run: .github/steps/install-hub

      - run: echo "::add-path::/opt/bin"

      - name: Update release candidate Github release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/scripts/release-tools dev-to-rc
