name: Update draft changelog on every dev PR

on:
  push:
    branches:
      - dev

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
#      # TODO This is really slow
#      - uses: release-drafter/release-drafter@v5
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Using a branch which has dockerless variant
      - uses: casz/release-drafter@chore/probot-adapter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
