name: Dev push

on:
  push:
    branches:
      - dev

jobs:
  update_draft_release_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=999 origin +refs/tags/*:refs/tags/*
      - run: git checkout dev
      - run: git log --merges v1.18..HEAD
      - id: cache
        uses: actions/cache@v1
        with:
          path: /opt/bin
          key: bins-${{ hashFiles('.github/scripts/install-bins') }}
      - name: Install bins
        if: steps.cache.outputs.cache-hit != 'true'
        run: .github/scripts/install-bins
      - run: echo "::add-path::/opt/bin"
      - name: Update draft release and it's changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/scripts/release-tools update_draft

  create_release_candidate_pull_request:
    runs-on: ubuntu-latest
    needs: update_draft_release_changelog
    steps:
      - uses: actions/checkout@v2
      - id: cache
        uses: actions/cache@v1
        with:
          path: /opt/bin
          key: ${{ hashFiles('.github/scripts/install-bins') }}
      - name: Install bins
        if: steps.cache.outputs.cache-hit != 'true'
        run: .github/scripts/install-bins
      - run: echo "::add-path::/opt/bin"
      - name: Create pull request from dev to rc, if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/scripts/pr-tools dev_to_rc

