name: On 'master' branch push

on:
  push:
    branches:
      - master

jobs:
  install-hub:
    runs-on: ubuntu-latest
    steps:
      - id: cache
        uses: actions/cache@v1
        with:
          path: /opt/bin
          key: opt-bin-hub-1
      - name: Install hub
        if: steps.cache.outputs.cache-hit != 'true'
        run: .github/steps/install-hub

  release_new_version:
    runs-on: ubuntu-latest
    needs: install-hub
    steps:
      - uses: actions/checkout@v2
      - name: Release a new version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/scripts/release-tools release_new_version
