name: On rc push

on:
  push:
    branches:
      - rc

jobs:
  install-hub:
    runs-on: ubuntu-latest
    steps:
    - id: cache
      uses: actions/cache@v1
      with:
        path: /opt/bin
        key: opt-bin-hub-1
    - name: Install hub
      if: steps.cache.outputs.cache-hit != 'true'
      run: .github/steps/install-hub

  update_pre_release:
    runs-on: ubuntu-latest
    needs: install-hub
    steps:
      - uses: actions/checkout@v2
      - name: Update release candidate Github release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/scripts/release-tools update_rc_change

  create_release_pr:
    runs-on: ubuntu-latest
    needs: install-hub
    steps:
      - uses: actions/checkout@v2
      - name: Create pull request from rc to master, if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/scripts/pr-tools rc_to_master
