name: Update current release candidate PR from dev

on:
  push:
    branches:
      - dev

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git checkout -b next-release-candidate
          git fetch origin next-release-candidate || echo "No remote branch yet."
          git push --set-upstream origin next-release-candidate --force-with-lease
      - id: cache
        uses: actions/cache@v1
        with:
          path: /opt/hub
          key: hub-2.1.4
      - name: Install hub
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p /opt/hub
          curl -L https://github.com/github/hub/releases/download/v2.14.0/hub-linux-amd64-2.14.0.tgz -o /tmp/hub.tgz
          tar xzf /tmp/hub.tgz -C /tmp
          mv /tmp/hub-*/bin/hub /opt/hub/hub
      - name: Create pull request if needed
        run: |
          hub pr list -f '%I' -h next-release-candidate
