name: Update current release candidate PR from dev

on:
  push:
    branches:
      - dev

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git checkout -b next-release-candidate
          git fetch origin next-release-candidate || echo "No remote branch yet."
          git push --set-upstream origin next-release-candidate --force-with-lease
